namespace SmartShopper.Api.Services.DualModel;

/// <summary>
/// Service for validation and correction using Gemini 2.0 Flash.
/// Validates and corrects output from the generator model.
/// </summary>
public interface IGeminiService
{
    /// <summary>
    /// Validates and corrects a draft recipe generated by Groq.
    /// </summary>
    /// <param name="draftRecipeJson">JSON string containing draft recipe from Groq</param>
    /// <param name="userInventory">List of ingredients available in user's fridge</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>JSON string containing validated and corrected recipe</returns>
    Task<string> ValidateAndCorrectRecipeAsync(
        string draftRecipeJson,
        List<string> userInventory,
        CancellationToken cancellationToken);

    /// <summary>
    /// Validates and corrects draft product recommendations generated by Groq.
    /// </summary>
    /// <param name="draftRecommendationsJson">JSON string containing draft recommendations from Groq</param>
    /// <param name="shoppingList">List of items user wants to purchase</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>JSON string containing validated and corrected recommendations</returns>
    Task<string> ValidateAndCorrectProductRecommendationsAsync(
        string draftRecommendationsJson,
        List<string> shoppingList,
        CancellationToken cancellationToken);
}
