namespace SmartShopper.Api.Services.DualModel;

/// <summary>
/// Interface for OpenAI validation service.
/// Used as the validator in the dual-model verification pipeline.
/// </summary>
public interface IOpenAIService
{
    /// <summary>
    /// Validates and corrects a recipe draft generated by Groq.
    /// </summary>
    /// <param name="draftRecipeJson">Draft recipe JSON from generator</param>
    /// <param name="userInventory">User's available ingredients</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Validated and corrected recipe JSON</returns>
    Task<string> ValidateAndCorrectRecipeAsync(
        string draftRecipeJson,
        List<string> userInventory,
        CancellationToken cancellationToken);

    /// <summary>
    /// Validates and corrects product recommendations generated by Groq.
    /// </summary>
    /// <param name="draftRecommendationsJson">Draft recommendations JSON from generator</param>
    /// <param name="shoppingList">User's shopping list</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Validated and corrected recommendations JSON</returns>
    Task<string> ValidateAndCorrectProductRecommendationsAsync(
        string draftRecommendationsJson,
        List<string> shoppingList,
        CancellationToken cancellationToken);
}
